"""add module config hash

Revision ID: 3cdeba46dbda
Revises: 001_initial_schema
Create Date: 2026-07-13 15:54:46.026892
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3cdeba46dbda"
down_revision = "001_initial_schema"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dotfile_modules", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("config_hash", sa.String(length=64), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dotfile_modules", schema=None) as batch_op:
        batch_op.drop_column("config_hash")

    # ### end Alembic commands ###
